name: Deploy to GitHub Pages
on:
  push:
    branches:
      - master
  workflow_dispatch:
jobs:
  build:
    runs-on: ubuntu-latest
    steps:

      - id: use-node-toolchain
        name: Use Node toolchain
        uses: actions/setup-node@v4
        with:
          node-version: '24'
          cache: 'yarn'

      - id: install-dependencies
        name: Install dependencies
        run: yarn

      - id: build-single-page-application
        name: Build Single Page Application
        run: yarn build

      - id: upload-production-build
        name: Upload production-ready build files
        uses: actions/upload-pages-artifact@v3
        with:
          name: github-pages
          path: ./dist


  deploy:
    if: github.ref == 'refs/heads/master'
    needs: build
    runs-on: ubuntu-latest

    permissions:
      pages: write
      contents: write
      id-token: write
      actions: read

    environment:
      name: github-pages
      url: ${{ steps.deployment.outputs.page_url }}

    steps:
      - name: Download artifact
        uses: actions/download-artifact@v4
        with:
          name: github-pages
          path: ./dist
      - name: Deploy to GitHub Pages
        id: deployment
        uses: actions/deploy-pages@v4